spring:
  application:
    name: g-40-shop
  datasource:
    url: jdbc:postgresql://localhost:5432/g_40_shop
    username: postgres
    password: qwerty007
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

key:
  access: Sf2/MZFPvvbKmQufF/XJ23MOpIV6cJysnEaQ7veRATU=
  refresh: N8VjRs2JtsJJpyB887zFbD4qye9loQxKx5iZ418V1Xs=

logging:
  file:
    name: logs/log.log
  level:
    root: info

messages:
  hello: Hello from local application!
